# Generated by Django 4.0.6 on 2022-07-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference_Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('occupancy', models.IntegerField()),
                ('max_booking_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('Hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.conference_hall')),
            ],
        ),
    ]
