# Generated by Django 4.0.6 on 2022-07-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_hall',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
