# Generated by Django 4.0.6 on 2022-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0003_conference_hall_occupied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=3)),
                ('url', models.URLField()),
            ],
        ),
    ]
