# Generated by Django 4.0.6 on 2022-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0005_dynamicpanel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='url',
            field=models.CharField(max_length=30),
        ),
    ]
