# Generated by Django 4.0.6 on 2022-07-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AoRole', '0006_alter_dynamicpanel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall_booking_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('Participant_count', models.IntegerField()),
                ('purpose', models.TextField()),
                ('emp_remark', models.TextField()),
                ('submit_time_emp', models.DateTimeField()),
                ('Hod_remark', models.TextField()),
                ('Hod_approval', models.BooleanField()),
                ('time_stamp_Hod', models.DateTimeField()),
                ('Ao_remark', models.TextField()),
                ('time_stamp_AO', models.DateTimeField()),
                ('booked', models.BooleanField(default=False)),
                ('Hall_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.conference_hall')),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.department')),
            ],
        ),
    ]
