# Generated by Django 4.0.6 on 2022-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0007_department_hall_booking_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_booking_form',
            name='Ao_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='Hod_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='Hod_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='emp_department',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='emp_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='time_stamp_AO',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='time_stamp_Hod',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
