# Generated by Django 4.0.6 on 2022-07-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0008_alter_hall_booking_form_ao_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.conference_hall')),
            ],
        ),
    ]
