# Generated by Django 4.0.6 on 2022-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0009_booked_hall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked_Hall',
        ),
    ]
