# Generated by Django 4.0.6 on 2022-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0011_conference_hall_from_date_conference_hall_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference_hall',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='hall_booking_form',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='hall_booking_form',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='conference_hall',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference_hall',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hall_booking_form',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
