# Generated by Django 4.0.6 on 2022-07-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0018_alter_hall_booking_form_emp_department_booked_hall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hall_booking_Form',
        ),
    ]
