# Generated by Django 4.0.6 on 2022-07-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0019_delete_hall_booking_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall_booking_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('Participant_count', models.IntegerField()),
                ('purpose', models.TextField()),
                ('emp_remark', models.TextField(blank=True, null=True)),
                ('submit_time_emp', models.DateTimeField()),
                ('Hod_remark', models.TextField(blank=True, null=True)),
                ('Hod_approval', models.BooleanField(blank=True, null=True)),
                ('time_stamp_Hod', models.DateTimeField(blank=True, null=True)),
                ('Ao_remark', models.TextField(blank=True, null=True)),
                ('time_stamp_AO', models.DateTimeField(blank=True, null=True)),
                ('booked', models.BooleanField(default=False)),
                ('Hall_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.conference_hall')),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AoRole.userdepartment')),
            ],
        ),
    ]
