# Generated by Django 4.0.6 on 2022-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0020_hall_booking_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_booking_form',
            name='booked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
