# Generated by Django 4.0.6 on 2022-07-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0021_alter_hall_booking_form_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference_hall',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='conference_hall',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='conference_hall',
            name='to_date',
        ),
    ]
