# Generated by Django 4.0.6 on 2022-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AoRole', '0023_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked_Hall',
        ),
    ]
